config/routes.rb
ShoppingCart::Engine.routes.draw do
  resources :orders, only: %i[index show]
  resources :order_items, only: %i[create update destroy]
  get 'cart', to: 'orders#cart', as: 'cart_page'
  post 'cart', to: 'orders#activate_coupon', as: 'activate_coupon'

  get 'checkout/start', to: 'checkout#start', as: 'checkout_start'
  get 'checkout(/:edit)', to: 'checkout#index', as: 'checkout'
  put 'checkout/edit_data', as: 'checkout_edit'
  get 'checkout/next_stage', to: redirect('checkout')
  put 'checkout/next_stage', as: 'checkout_next'
end

app/models/concerns/shopping_cart/address_validator.rb
module ShoppingCart
  module AddressValidator
    extend ActiveSupport::Concern
    included do
      validates :first_name, :last_name, :address, :city, :zip, :country, :phone, presence: true

      validates :phone, length: { in: 6..15 }, format: { with: /\A[+][\d]+\z/ }
      validates :zip, length: { in: 3..10 }, format: { with: /\A([\d]\-?)+\z/ }
      validates :city, length: { in: 2..50 }, format: { with: /\A([a-zA-Z\s])+\z/ }
      validates :address, length: { in: 2..50 }, format: { with: /\A([a-zA-Z\s\d][\,\-]?)+\z/ }
      validates :last_name, :first_name, length: { in: 2..50 }, format: { with: /\A([a-zA-Z])+\z/ }
    end
  end
end

app/models/concerns/shopping_cart/credit_card_validator.rb
module ShoppingCart
  class CreditCardValidator < ActiveModel::Validator
    def validate(record)
      expire_time = safe_date(record.expires)

      if expire_time.nil?
        record.errors[:expires] << I18n.t('activerecord.credit_card.validation.expires_invalid')
      elsif Time.now > expire_time
        record.errors[:expires] << I18n.t('activerecord.credit_card.validation.expired')
      end
    end

    private

    def safe_date(expires, default = nil)
      splitted = expires&.split('/')
      Time.new('20' << splitted[1], splitted[0])
    rescue StandardError
      default
    end
  end
end

app/models/shopping_cart/application_record.rb
module ShoppingCart
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/shopping_cart/billing_address.rb
module ShoppingCart
  class BillingAddress < ApplicationRecord
    belongs_to :billing_a, polymorphic: true
    include AddressValidator
  end
end

app/models/shopping_cart/coupon.rb
module ShoppingCart
  class Coupon < ApplicationRecord
    has_many :orders, dependent: :nullify
  end
end

app/models/shopping_cart/credit_card.rb
module ShoppingCart
  class CreditCard < ApplicationRecord
    include ActiveModel::Validations
    validates_with CreditCardValidator
    validates :number, :name, :expires, :cvv, presence: true
    validates :number, length: { is: 16 }, numericality: { only_integer: true }
    validates :name, length: { in: 2..49 }, format: { with: /\A[a-zA-Z\s]+\z/ }
    validates :expires, format: { with: %r{\A(0[1-9]|10|11|12)\/\d\d\z} }
    validates :cvv, length: { is: 3 }, numericality: { only_integer: true }

    belongs_to :order
  end
end

app/models/shopping_cart/delivery_method.rb
module ShoppingCart
  class DeliveryMethod < ApplicationRecord
    has_many :orders, dependent: :nullify
    validates :name, :cost, :delay, presence: true
  end
end

app/models/shopping_cart/order.rb
module ShoppingCart
  class Order < ApplicationRecord
    include AASM
    belongs_to :user, optional: true, class_name: ShoppingCart.user_class.to_s

    aasm column: 'checkout_state' do
      state :address, initial: true
      state :delivery
      state :payment
      state :confirm
      state :complete

      event :reset_state do
        transitions to: :address
      end

      event :next_state do
        transitions from: :address, to: :delivery
        transitions from: :delivery, to: :payment
        transitions from: :payment, to: :confirm
        transitions from: :confirm, to: :complete
      end
    end

    belongs_to :delivery_method, optional: true
    belongs_to :coupon, optional: true
    has_one :billing_address, as: :billing_a, dependent: :destroy
    has_one :shipping_address, as: :shipping_a, dependent: :destroy
    accepts_nested_attributes_for :billing_address, allow_destroy: true
    accepts_nested_attributes_for :shipping_address, allow_destroy: true
    has_many :order_items, dependent: :destroy
    has_many :products, through: :order_items

    has_one :credit_card, dependent: :destroy
    accepts_nested_attributes_for :credit_card

    enum status: %i[in_progress in_queue in_delivery delivered canceled]

    scope :completed, -> { where.not(status: :in_progress) }
    scope :select_status, ->(val) { where(status: val) unless val.nil? }

    def total_quantity
      order_items.pluck(:quantity).sum
    end

    def coupon_discount
      coupon.nil? ? 0 : coupon.discount
    end

    def subtotal
      order_items.collect { |item| item.quantity * item.product.price }.sum
    end

    def total_items
      subtotal - coupon_discount
    end

    def pre_total_price
      subtotal + delivery_price - coupon_discount
    end

    def delivery_price
      delivery_method&.cost || 0
    end
  end
end

app/models/shopping_cart/order_item.rb
module ShoppingCart
  class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product, class_name: ShoppingCart.product_class.to_s
  end
end

app/models/shopping_cart/shipping_address.rb
module ShoppingCart
  class ShippingAddress < ApplicationRecord
    belongs_to :shipping_a, polymorphic: true
    include AddressValidator
  end
end

app/controllers/shopping_cart/application_controller.rb
module ShoppingCart
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
    before_action :last_order
  end
end

app/controllers/shopping_cart/checkout_controller.rb
require_dependency "shopping_cart/application_controller"

module ShoppingCart
  class CheckoutController < ApplicationController
    before_action :authenticate_user!, except: [:start]
    before_action :save_cart_after_login, :init, :check_order_not_empty

    def start
      start_save_cart_if_no_auth
      cookies.delete(:return_to_confirm)
      redirect_to :checkout
    end

    def index
      @form = CheckoutForm.new(@order)
    end

    def edit_data
      @order.checkout_state = state_params[:type]
      return unless @order.save
      cookies[:return_to_confirm] = true
      redirect_to :checkout
    end

    def next_stage
      status = @service.next_stage(@state_layout)
      @service.return_to_confirm_if_need(status)
      if status == :success
        save_order_for_last_step if @state_layout == 'confirm'
        return redirect_to :checkout
      end
      @form = CheckoutForm.new(@order)
      render 'index'
    end

    private

    def init
      @user = current_user
      @order = select_order.decorate
      @state_layout = @order.checkout_state
      @service = CheckoutService.new(params, cookies, @user, @order)
    end

    def check_order_not_empty
      return unless @order.order_items.blank?
      @order.reset_state! unless @order.address?
      flash[:alert] = t('checkout.emptycart')
      redirect_to cart_page_url
    end

    def select_order
      last_completed_order_id = cookies[:last_completed_order_id]
      return last_order if last_completed_order_id.nil?
      cookies.delete(:last_completed_order_id)
      @user.orders.find_by(id: last_completed_order_id)
    end

    def save_order_for_last_step
      cookies[:last_completed_order_id] = @order.id
    end

    def start_save_cart_if_no_auth
      return if user_signed_in?
      cookies[:save_cart] = true unless last_order.order_items.blank?
    end

    def save_cart_after_login
      return unless cookies[:save_cart]
      order = guest_order
      return unless order
      last_order.destroy
      order.update_attributes(user: current_user)
      clear_guest_cookies
    end

    def state_params
      params.permit(:type)
    end
  end
end

app/controllers/shopping_cart/order_items_controller.rb
require_dependency "shopping_cart/application_controller"

module ShoppingCart
  class OrderItemsController < ApplicationController
    authorize_resource

    def create
      item = last_order.order_items.find_by(product_id: filtered_params[:product_id])
      if item
        item.increment(:quantity, filtered_params[:quantity])
      else
        item = last_order.order_items.build(filtered_params)
      end
      flash[:notice] = item.save ? t('order_item.create_success') : t('order_item.create_fail')
      redirect_back(fallback_location: cart_page_path)
    end

    def update
      item = last_order.order_items.find_by(id: params[:id])
      flash[:alert] = t('order_item.update_fail') unless item&.update_attributes(filtered_params)
      redirect_back(fallback_location: cart_page_path)
    end

    def destroy
      cart = last_order.order_items
      cart.destroy(params[:id]) if cart.exists?(params[:id])
      redirect_back(fallback_location: cart_page_path)
    end

    private

    def quantity_param
      order_item_params[:quantity].to_i <= 0 ? 1 : order_item_params[:quantity].to_i
    end

    def filtered_params
      order_item_params.merge(quantity: quantity_param)
    end

    def order_item_params
      params.require(:order_item).permit(:id, :product_id, :quantity)
    end
  end
end

app/controllers/shopping_cart/orders_controller.rb
require_dependency "shopping_cart/application_controller"

module ShoppingCart
  class OrdersController < ApplicationController
    authorize_resource :order, only: %i[index show]

    def index
      @orders = current_user.orders.completed
                            .select_status(params[:status])
                            .decorate
    end

    def show
      @order = current_user.orders.completed.find(params[:id]).decorate
    end

    def cart
      @order = last_order.decorate
    end

    def activate_coupon
      service = OrderService.new(last_order)
      msg = service.activate_coupon_with_message(coupon_params[:coupon_id])
      redirect_to cart_page_url, flash: { notice: msg }
    end

    private

    def coupon_params
      params.require(:order).permit(:coupon_id)
    end
  end
end

app/helpers/shopping_cart/application_helper.rb
module ShoppingCart
  module ApplicationHelper
  end
end

app/helpers/shopping_cart/orders_helper.rb
module ShoppingCart
  module OrdersHelper
    def order_filters
      Order.statuses.select { |_, val| val.positive? }
    end

    def active_order_filter
      filter = params[:status].to_i
      selected = Order.statuses.keys[filter]
      return I18n.t('orders.filter.all') if filter.zero? || selected.nil?
      I18n.t("orders.status.#{selected}")
    end
  end
end

app/views/shopping_cart/orders/_filter.html.haml
%a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
  = active_order_filter
  %i.fa.fa-angle-down.dropdown-icon.pull-right
%ul.dropdown-menu
  %li
    = link_to t('orders.filter.all'), orders_path
  - order_filters.each do |item|
    %li
      = link_to t("orders.status.#{item[0]}"), orders_path(status: item[1])

app/views/shopping_cart/orders/cart.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= t('cart.title')
  %table.table.table-hover
    %tr.no-hover
      %th.col-pic.pl-0
        %span.in-grey-600= t('cart.itemlist.product')
      %th.col-title
      %th.col-price
        %span.in-grey-600= t('cart.itemlist.price')
      %th.col-quantity
        %span.in-grey-600= t('cart.itemlist.quantity')
      %th.col-total
        %span.in-grey-600= t('cart.itemlist.subtotal')
      %th.col-close
    - if @order.items.count.zero?
      %tr
        %td{colspan: 6}
          .text-center
            = t('cart.empty')
    - @order.items.each do |order_item|
      - item = order_item.product
      %tr
        %td
          .general-img-wrap-table
            image
        %td
          %p.title= item.name
        %td
          %span.font-16.in-gold-500= number_to_currency(item.price)
        %td
          .input-group
            = simple_form_for order_item do |f|
              - if order_item.quantity.to_i == 1
                %a{href:"javascript:void(0)", class: 'input-link'}
                  %i.fa.fa-minus.line-heaght-40
              - else
                = link_to order_item_path(order_item, order_item: { quantity: order_item.quantity - 1 } ), method: "patch", class: "input-link" do
                  %i.fa.fa-minus.line-heaght-40
              = f.input_field :quantity, as: :string, value: order_item.quantity, label: false, class: "form-control quantity-input"
              = link_to order_item_path(order_item, order_item: { quantity: order_item.quantity + 1 } ), method: "patch", class: "input-link" do
                %i.fa.fa-plus.line-heaght-40
        %td
          %span.font-16.in-gold-500= number_to_currency((order_item.quantity * item.price))
        %td
          = link_to order_item_path(order_item), method: "delete", class: "close general-cart-close" do
            %span{'aria-hidden': "true"} &times;
  .general-order-wrap
    .row
      .col-sm-4
        = simple_form_for @order, method: :post, url: activate_coupon_path, html: { novalidate: false } do |f|
          .input-group.general-input-group
            %label.input-label= t('cart.coupon.enteryourcode')
            = f.input :coupon_id, input_html: {placeholder: "#{t('cart.coupon.enteryourcode')}", class: "form-control mb-30", type: "text", value: ""}, required: true, label: false
            %div
              = f.button :submit, t('cart.coupon.apply'), class: "btn btn-primary mr-5 mb-15 visible-xs-inline-block"
              = f.button :submit, t('cart.coupon.updcart'), class: "btn btn-primary mb-15 res-block"
      .col-sm-8
        .res-mr-200.text-center.general-text-right
          %p.in-gold-500.font-18= t('cart.total.ordersumm')
          %table.general-summary-table.general-summary-table-right.general-text-right
            %tr
              %td
                %p.font-16= "#{t('cart.total.ordersumm')}:"
              %td
                %p.font-16= number_to_currency(@order.subtotal)
            %tr
              %td
                %p.font-16= "#{t('cart.total.coupon')}:"
              %td
                %p.font-16= number_to_currency(@order.coupon_discount)
            %tr
              %td
                %strong.font-18= "#{t('cart.total.ordertotal')}:"
              %td
                %strong.font-18= number_to_currency(@order.total_items)
  .text-center
    = link_to t('cart.checkout'), checkout_start_path, class: "btn btn-default mb-20 hidden-xs"

app/views/shopping_cart/orders/index.html.haml
%main.container.general-main-wrap
  %h1.mt-0.mb-25= t('orders.title')
  %p.lead.small.mb-10.visible-xs= t('orders.filterby')
  .dropdowns.dropdown.general-order-dropdown
    = render partial: 'filter'
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600= t('orders.list.number')
        %th
          %span.in-grey-600= t('orders.list.completedat')
        %th
          %span.in-grey-600= t('orders.list.status')
        %th
          %span.in-grey-600= t('orders.list.total')
    %tbody
      - if @orders.count.zero?
        %tr
          %td{colspan: 4, style: "text-align: center;"}
            = t('orders.donthaveorders')
      - @orders.each do |order|
        %tr
          %td
            = link_to "##{order.number}", order_path(order), class: "general-order-number"
          %td
            %span.in-grey-900.font-16.fw-300= order.format_mdate
          %td
            %span.font-16.in-grey-900.fw-300= order.format_status
          %td
            %strong.font-16= number_to_currency(order.total_price)

app/views/shopping_cart/orders/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= "#{t('checkout.order')} R#{@order.number}"
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle.mt-0= t('checkout.address.shaddress')
      %p.general-address
        = "#{@order.shipping_address.first_name} #{@order.shipping_address.last_name}"
        %br
        = @order.shipping_address.address
        %br
        = "#{@order.shipping_address.city} #{@order.shipping_address.zip}"
        %br
        = @order.shipping_address.country
        %br
        = "Phone #{@order.shipping_address.phone}"
    .col-sm-3
      %h3.general-subtitle.mt-0= t('checkout.address.billaddress')
      %p.general-address
        = "#{@order.billing_address.first_name} #{@order.billing_address.last_name}"
        %br
        = @order.billing_address.address
        %br
        = "#{@order.billing_address.city} #{@order.billing_address.zip}"
        %br
        = @order.billing_address.country
        %br
        = "Phone #{@order.billing_address.phone}"
    .col-sm-3
      %h3.general-subtitle.mt-0= t('checkout.confirm.shipments')
      %p.general-address
        = @order.delivery_method.try(:name)
        %br
        = "Cost #{number_to_currency(@order.delivery_method.try(:cost)}"
    .col-sm-3
      %h3.general-subtitle.mt-0= t('checkout.confirm.paymentinfo')
      %p.general-address
        = @order.short_card_number
        %br
        = @order.credit_card.expires
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600= t('checkout.itemlist.book')
        %th.col-method
        %th
          %span.in-grey-600= t('checkout.itemlist.price')
        %th
          %span.in-grey-600= t('checkout.itemlist.quantity')
        %th
          %span.in-grey-600= t('checkout.itemlist.total')
    %tbody
      - @order.items.each do |order_item|
        - item = order_item.product
        %tr
          %td
            .general-img-wrap-table
              img
          %td
            %p.title= item.name
          %td
            %span.font-16.in-gold-500= number_to_currency(item.price
          %td
            %span.ml-30= order_item.quantity
          %td
            %span.font-16.in-gold-500= number_to_currency((order_item.quantity * item.price)
  .text-center.general-text-right
    %p.in-gold-500.font-18= t('checkout.ordersumm')
    %table.general-summary-table.general-summary-table-right.general-text-right
      = render partial: "shopping_cart/checkout/cost", object: @order